# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:49
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import protected_media.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_file', models.FileField(upload_to='collection')),
                ('protected_file', protected_media.models.ProtectedFileField(storage=django.core.files.storage.FileSystemStorage(base_url=b'protected/', location=b'/home/cobusc/git-projects/django-protected-media-prototype/protected/'), upload_to='collection')),
            ],
        ),
    ]
