sudo: true
language: python
jobs:
  include:
# https://docs.djangoproject.com/en/4.1/releases/2.2/
  - env: DJANGO_VERSION=2.2
    python: "3.5"
    dist: xenial
  - env: DJANGO_VERSION=2.2
    python: "3.6"
  - env: DJANGO_VERSION=2.2
    python: "3.7"
    dist: xenial
  - env: DJANGO_VERSION=2.2
    python: "3.8"
    dist: xenial
  - env: DJANGO_VERSION=2.2
    python: "3.9"
    dist: xenial
# https://docs.djangoproject.com/en/4.1/releases/3.0/
  - env: DJANGO_VERSION=3.0
    python: "3.6"
    dist: bionic
  - env: DJANGO_VERSION=3.0
    python: "3.7"
    dist: bionic
  - env: DJANGO_VERSION=3.0
    python: "3.8"
    dist: bionic
  - env: DJANGO_VERSION=3.0
    python: "3.9"
    dist: bionic
# https://docs.djangoproject.com/en/4.1/releases/3.1/
  - env: DJANGO_VERSION=3.1
    python: "3.6"
    dist: bionic
  - env: DJANGO_VERSION=3.1
    python: "3.7"
    dist: bionic
  - env: DJANGO_VERSION=3.1
    python: "3.8"
    dist: bionic
  - env: DJANGO_VERSION=3.1
    python: "3.9"
    dist: bionic
# https://docs.djangoproject.com/en/4.1/releases/3.2/
  - env: DJANGO_VERSION=3.2
    python: "3.6"
    dist: bionic
  - env: DJANGO_VERSION=3.2
    python: "3.7"
    dist: bionic
  - env: DJANGO_VERSION=3.2
    python: "3.8"
    dist: bionic
  - env: DJANGO_VERSION=3.2
    python: "3.9"
    dist: bionic
  - env: DJANGO_VERSION=3.2
    python: "3.10"
    dist: bionic
# https://docs.djangoproject.com/en/4.1/releases/4.0/
  - env: DJANGO_VERSION=4.0
    python: "3.8"
    dist: jammy
  - env: DJANGO_VERSION=4.0
    python: "3.9"
    dist: jammy
  - env: DJANGO_VERSION=4.0
    python: "3.10"
    dist: jammy
# https://docs.djangoproject.com/en/4.1/releases/4.1/
  - env: DJANGO_VERSION=4.1
    python: "3.8"
    dist: jammy
  - env: DJANGO_VERSION=4.1
    python: "3.9"
    dist: jammy
  - env: DJANGO_VERSION=4.1
    python: "3.10"
    dist: jammy
  - env: DJANGO_VERSION=4.1
    python: "3.11"
    dist: jammy


addons:
  apt:
    packages:
    - nginx

install:
    - sudo cp tests/nginx.conf /etc/nginx/
    - sudo service nginx reload
    - pip install --upgrade importlib-metadata
    - pip install -q Django==$DJANGO_VERSION .

script:
    - make test
