sudo: true
language: python
jobs:
  include:
  - env: DJANGO_VERSION=2.2
    python: "3.5"
  - env: DJANGO_VERSION=2.2
    python: "3.6"
  - env: DJANGO_VERSION=2.2
    python: "3.7"
  - env: DJANGO_VERSION=2.2
    python: "3.8"
  - env: DJANGO_VERSION=3.0
    python: "3.6"
  - env: DJANGO_VERSION=3.0
    python: "3.7"
  - env: DJANGO_VERSION=3.0
    python: "3.8"
  - env: DJANGO_VERSION=3.1
    python: "3.6"
  - env: DJANGO_VERSION=3.1
    python: "3.7"
  - env: DJANGO_VERSION=3.1
    python: "3.8"
  - env: DJANGO_VERSION=3.1
    python: "4.0"


addons:
  apt:
    packages:
    - nginx

install:
    - sudo ln -s tests/ngingx.conf /etc/nginx/sites-enabled/
    - sudo service nginx reload
    - pip install -q Django==$DJANGO_VERSION
    - python setup.py -q install

script:
    - make test
